### ISSUE TITLE
Bug: Function may return unintended value

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/InSilicoVA#10]
The function scale.vec.inter could potentially return NULL. If scale is NULL and scale.max is NULL what is returned?

https://github.com/verbal-autopsy-software/InSilicoVA/blob/7f5169a4477cc5f6fca7a68bf9c12758bd94d915/InSilicoVA/R/insilico_core.r#L141-L157

**Comment by richardli** [comment]
You are right. In that case it will return NULL. It's always called with one non-null values, so internally it's not causing problems. I'll change it though, so it's not causing confusions when reading the codes. 

On the to-do list. Thanks!
