### ISSUE TITLE
Bug: Misleading comment says loop over causes, but code looping over symptoms

### ISSUE THREAD

**Issue by mjutras-mitre** [verbal-autopsy-software/InSilicoVA#15]
https://github.com/verbal-autopsy-software/InSilicoVA/blob/7f5169a4477cc5f6fca7a68bf9c12758bd94d915/InSilicoVA/java/Insilico/src/sampler/InsilicoSampler2.java#L368-L369

**Comment by richardli** [comment]
7f770ac7ab8d82c1b9de25debc7e734f06273df8, thanks
