### ISSUE TITLE
Processing CondProb argument in insilico_core.r 

### ISSUE THREAD

**Issue by jarathomas** [verbal-autopsy-software/InSilicoVA#28]
Lines 918 to 923 in insilico_core.r set up CondProb (but they also rely on CondProbNum):

	  	if(!is.null(CondProb)){
	  		prob.orig <- CondProb
	  		exclude.impossible.cause <- "none"
	  		vacauses <- colnames(CondProbNum)   # SHOULD THIS JUST BE CondProb?
	  		if(is.null(vacauses)) vacauses <- paste0("Cause", 1:dim(CondProbNum)[2])  # Use CondProb here too?
	  	}

**Comment by richardli** [comment]
Yes I think using CondProb will be better inside the loop. If you are making changes now please feel free to change both instances in there to `Condprob`. Thanks!

**Comment by jarathomas** [comment]
Made the change in: https://github.com/verbal-autopsy-software/InSilicoVA/commit/9bf7597dce812bdf7edfc3faf8f518c0e3976aa8
